# version: '3'

# services:

#   backend:
#     build:
#       context: ./Backend
#     ports:
#       - 8000:8000

version: '3'
services:
  postgresql:
    image: postgres
    # restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=root
    volumes:
      - pgsql:/var/lib/postgresql/data
volumes:
  pgsql:
    driver: local