# version: '3'

# services:

#   mongodb:
#     image: mongo
#     ports:
#       - 27017:27017
#     environment:
#       - MONGO_INITDB_ROOT_USERNAME=root
#       - MONGO_INITDB_ROOT_PASSWORD=root
#     volumes:
#       - mongo-data:/data/db

#   mongo-express:
#     image: mongo-express
#     ports:
#       - 8081:8081
#     environment:
#       # - ME_CONFIG_BASICAUTH_USERNAME=root
#       # - ME_CONFIG_BASICAUTH_PASSWORD=root
#       - ME_CONFIG_MONGODB_ADMINUSERNAME=root
#       - ME_CONFIG_MONGODB_ADMINPASSWORD=root
#       - ME_CONFIG_MONGODB_SERVER=mongodb      
  
# volumes:
#   mongo-data:
#     driver: local

version: '3'
services:
  postgresql:
    image: postgres
    # restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=root
    volumes:
      - pgsql:/var/lib/postgresql/data
volumes:
  pgsql:
    driver: local
  restart: always
